<?php
// Database configuration
define('DB_HOST', 'localhost'); // Change to your database host
define('DB_USER', 'root');      // Change to your database username
define('DB_PASS', '');          // Change to your database password
define('DB_NAME', 'school_db'); // Change to your database name

// Connect to the database
$conn = new mysqli(DB_HOST, DB_USER, DB_PASS, DB_NAME);

// Check the connection
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}

// Start session to get principal's ID
session_start();
if (isset($_SESSION['user_id'])) {
    $principalId = $_SESSION['user_id'];

    // Fetch reports generated by the logged-in principal
    $stmt = $conn->prepare("SELECT * FROM Reports");
    $stmt->bind_param("i", $principalId);
    $stmt->execute();
    $result = $stmt->get_result();
} else {
    echo "<script>alert('Please login first.'); window.location.href='login.php';</script>";
    exit();
}

// Close the connection
$conn->close();
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>View Reports</title>
</head>
<body>
    <h2>Your Reports</h2>
    <?php if ($result->num_rows > 0): ?>
        <table border="1">
            <tr>
                <th>Report ID</th>
                <th>Principal_ID</th>
                <th>Content</th>
                <th>Generated At</th>
                <th>Student Id</th>
            </tr>
            <?php while ($row = $result->fetch_assoc()): ?>
                <tr>
                    <td><?php echo $row['R_ID']; ?></td>
                    <td><?php echo $row['Principal_ID']; ?></td>
                    <td><?php echo $row['Content']; ?></td>
                    <td><?php echo $row['Generated_At']; ?></td>
                    <td><?php echo $row['studentId']; ?></td>
                </tr>
            <?php endwhile; ?>
        </table>
    <?php else: ?>
        <p>No reports found.</p>
    <?php endif; ?>
</body>
</html>